//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisosAUsuarios
    {
        public int idpermisosAUsuarios { get; set; }
        public Nullable<int> idusuario { get; set; }
        public Nullable<int> idventana { get; set; }
        public Nullable<int> insertar { get; set; }
        public Nullable<int> modificar { get; set; }
        public Nullable<int> eliminar { get; set; }
        public Nullable<int> consultar { get; set; }
    }
}
