//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class prestamoEnc
    {
        public int CodPrestamo { get; set; }
        public string cedula { get; set; }
        public Nullable<System.DateTime> fechaPrestamo { get; set; }
        public Nullable<System.DateTime> fechaDevoluvion { get; set; }
    }
}
